services:
  - type: web
    name: disaster-response-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        fromDatabase:
          name: disaster-response-db
          property: connectionString
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
    healthCheckPath: /api/health
    
databases:
  - name: disaster-response-db
    databaseName: disaster_response
    user: disaster_user
    plan: free
